# Generated by Django 5.1.6 on 2025-03-18 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("PATRON", "Patron"), ("LIBRARIAN", "Librarian")],
                        default="PATRON",
                        max_length=20,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "height",
                    models.CharField(
                        blank=True,
                        help_text="Height in cm or feet/inches",
                        max_length=10,
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True, help_text="Weight in kg or lbs", max_length=10
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preferred_rental_duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("SEASONAL", "Seasonal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "boot_size",
                    models.CharField(
                        blank=True, help_text="Boot size (US, EU, etc.)", max_length=10
                    ),
                ),
                (
                    "preferred_activity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SKIING", "Skiing"),
                            ("SNOWBOARDING", "Snowboarding"),
                            ("BOTH", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preferred_terrain",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GROOMED", "Groomed runs"),
                            ("POWDER", "Powder"),
                            ("PARK", "Park and pipe"),
                            ("ALLMOUNTAIN", "All-mountain"),
                            ("BACKCOUNTRY", "Backcountry"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "insurance_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ALWAYS", "Always add insurance"),
                            ("ASK", "Ask each time"),
                            ("NEVER", "Never add insurance"),
                        ],
                        default="ASK",
                        max_length=20,
                    ),
                ),
                ("receive_email_reminders", models.BooleanField(default=True)),
                ("receive_sms_reminders", models.BooleanField(default=False)),
                ("receive_marketing_emails", models.BooleanField(default=True)),
                ("is_public_profile", models.BooleanField(default=True)),
                ("show_rental_history", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
