# Generated by Django 5.1.6 on 2025-04-30 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('RENTAL_REQUEST', 'Rental Request'), ('RENTAL_APPROVED', 'Rental Approved'), ('RENTAL_DENIED', 'Rental Denied'), ('COLLECTION_REQUEST', 'Collection Access Request'), ('COLLECTION_APPROVED', 'Collection Access Approved'), ('COLLECTION_DENIED', 'Collection Access Denied')], max_length=30)),
                ('message', models.TextField()),
                ('related_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
