# Generated by Django 5.1.6 on 2025-03-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_collection_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='rental_duration',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('SEASONAL', 'Seasonal')], default='DAILY', max_length=20),
        ),
    ]
