# Generated by Django 5.1.6 on 2025-03-28 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_cartitem_rental_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rental rate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='seasonal_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Seasonal rental rate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weekly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weekly rental rate', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('SKI', 'Skis'), ('SNOWBOARD', 'Snowboard'), ('POLES', 'Ski Poles'), ('BOOTS', 'Boots'), ('HELMET', 'Helmet'), ('GOGGLES', 'Goggles'), ('GLOVES', 'Gloves'), ('JACKET', 'Jacket'), ('PANTS', 'Pants'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='recommended_skill_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert'), ('ALL', 'All Levels')], max_length=20),
        ),
    ]
