# Generated by Django 5.1.6 on 2025-03-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_cartitem_end_date_alter_cartitem_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_subtype',
            field=models.CharField(blank=True, choices=[('POWDER', 'Powder'), ('ALL_MOUNTAIN', 'All Mountain'), ('FREESTYLE', 'Freestyle'), ('FREERIDE', 'Freeride'), ('TOURING', 'Touring'), ('CARVING', 'Carving'), ('FRONTSIDE', 'Frontside')], max_length=20, null=True),
        ),
    ]
