# Generated by Django 5.1.6 on 2025-03-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_equipment_equipment_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_subtype',
            field=models.CharField(blank=True, choices=[('POWDER', 'Powder'), ('ALL_MOUNTAIN', 'All Mountain'), ('FREESTYLE', 'Freestyle'), ('FREERIDE', 'Freeride'), ('TOURING', 'Touring'), ('CARVING', 'Carving'), ('FRONTSIDE', 'Frontside'), ('SKI_BLADES', 'Ski Blades')], max_length=20, null=True),
        ),
    ]
