# Generated by Django 5.1.6 on 2025-04-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_equipment_equipment_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
