# Generated by Django 5.1.6 on 2025-04-28 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_equipment_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='sharing_type',
            field=models.CharField(choices=[('PUBLIC', 'Public - Visible to everyone'), ('PRIVATE', 'Private - Only visible to me'), ('SHARED', 'Shared - Only visible to selected users')], default='PUBLIC', max_length=20),
        ),
        migrations.CreateModel(
            name='CollectionAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=10)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='equipment.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('collection', 'user')},
            },
        ),
    ]
