# Generated by Django 5.1.6 on 2025-04-29 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_collection_sharing_type_collectionaccessrequest'),
    ]

    operations = [
    ]
