# Generated by Django 5.1.6 on 2025-04-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_convert_shared_to_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='sharing_type',
            field=models.CharField(choices=[('PUBLIC', 'Public - Visible to everyone'), ('PRIVATE', 'Private - Only visible to selected users')], default='PUBLIC', max_length=20),
        ),
    ]
