# Generated by Django 5.1.6 on 2025-05-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_alter_collection_sharing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='hourly_rate',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='rental_duration',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('SEASONAL', 'Seasonal')], default='DAILY', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_duration',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('SEASONAL', 'Seasonal')], max_length=20),
        ),
    ]
